pragma Singleton

import Quickshell

// Emoji para o prefixo ":" do lançador (gerado a partir do Unicode).
Singleton {
    readonly property var list: [
        ["\ud83c\udf00", "cyclone"],
        ["\ud83c\udf01", "foggy"],
        ["\ud83c\udf02", "closed umbrella"],
        ["\ud83c\udf03", "night with stars"],
        ["\ud83c\udf04", "sunrise over mountains"],
        ["\ud83c\udf05", "sunrise"],
        ["\ud83c\udf06", "cityscape at dusk"],
        ["\ud83c\udf07", "sunset over buildings"],
        ["\ud83c\udf08", "rainbow"],
        ["\ud83c\udf09", "bridge at night"],
        ["\ud83c\udf0a", "water wave"],
        ["\ud83c\udf0b", "volcano"],
        ["\ud83c\udf0c", "milky way"],
        ["\ud83c\udf0d", "earth globe europe-africa"],
        ["\ud83c\udf0e", "earth globe americas"],
        ["\ud83c\udf0f", "earth globe asia-australia"],
        ["\ud83c\udf10", "globe with meridians"],
        ["\ud83c\udf11", "new moon symbol"],
        ["\ud83c\udf12", "waxing crescent moon symbol"],
        ["\ud83c\udf13", "first quarter moon symbol"],
        ["\ud83c\udf14", "waxing gibbous moon symbol"],
        ["\ud83c\udf15", "full moon symbol"],
        ["\ud83c\udf16", "waning gibbous moon symbol"],
        ["\ud83c\udf17", "last quarter moon symbol"],
        ["\ud83c\udf18", "waning crescent moon symbol"],
        ["\ud83c\udf19", "crescent moon"],
        ["\ud83c\udf1a", "new moon with face"],
        ["\ud83c\udf1b", "first quarter moon with face"],
        ["\ud83c\udf1c", "last quarter moon with face"],
        ["\ud83c\udf1d", "full moon with face"],
        ["\ud83c\udf1e", "sun with face"],
        ["\ud83c\udf1f", "glowing star"],
        ["\ud83c\udf20", "shooting star"],
        ["\ud83c\udf21", "thermometer"],
        ["\ud83c\udf22", "black droplet"],
        ["\ud83c\udf23", "white sun"],
        ["\ud83c\udf24", "white sun with small cloud"],
        ["\ud83c\udf25", "white sun behind cloud"],
        ["\ud83c\udf26", "white sun behind cloud with rain"],
        ["\ud83c\udf27", "cloud with rain"],
        ["\ud83c\udf28", "cloud with snow"],
        ["\ud83c\udf29", "cloud with lightning"],
        ["\ud83c\udf2a", "cloud with tornado"],
        ["\ud83c\udf2b", "fog"],
        ["\ud83c\udf2c", "wind blowing face"],
        ["\ud83c\udf2d", "hot dog"],
        ["\ud83c\udf2e", "taco"],
        ["\ud83c\udf2f", "burrito"],
        ["\ud83c\udf30", "chestnut"],
        ["\ud83c\udf31", "seedling"],
        ["\ud83c\udf32", "evergreen tree"],
        ["\ud83c\udf33", "deciduous tree"],
        ["\ud83c\udf34", "palm tree"],
        ["\ud83c\udf35", "cactus"],
        ["\ud83c\udf36", "hot pepper"],
        ["\ud83c\udf37", "tulip"],
        ["\ud83c\udf38", "cherry blossom"],
        ["\ud83c\udf39", "rose"],
        ["\ud83c\udf3a", "hibiscus"],
        ["\ud83c\udf3b", "sunflower"],
        ["\ud83c\udf3c", "blossom"],
        ["\ud83c\udf3d", "ear of maize"],
        ["\ud83c\udf3e", "ear of rice"],
        ["\ud83c\udf3f", "herb"],
        ["\ud83c\udf40", "four leaf clover"],
        ["\ud83c\udf41", "maple leaf"],
        ["\ud83c\udf42", "fallen leaf"],
        ["\ud83c\udf43", "leaf fluttering in wind"],
        ["\ud83c\udf44", "mushroom"],
        ["\ud83c\udf45", "tomato"],
        ["\ud83c\udf46", "aubergine"],
        ["\ud83c\udf47", "grapes"],
        ["\ud83c\udf48", "melon"],
        ["\ud83c\udf49", "watermelon"],
        ["\ud83c\udf4a", "tangerine"],
        ["\ud83c\udf4b", "lemon"],
        ["\ud83c\udf4c", "banana"],
        ["\ud83c\udf4d", "pineapple"],
        ["\ud83c\udf4e", "red apple"],
        ["\ud83c\udf4f", "green apple"],
        ["\ud83c\udf50", "pear"],
        ["\ud83c\udf51", "peach"],
        ["\ud83c\udf52", "cherries"],
        ["\ud83c\udf53", "strawberry"],
        ["\ud83c\udf54", "hamburger"],
        ["\ud83c\udf55", "slice of pizza"],
        ["\ud83c\udf56", "meat on bone"],
        ["\ud83c\udf57", "poultry leg"],
        ["\ud83c\udf58", "rice cracker"],
        ["\ud83c\udf59", "rice ball"],
        ["\ud83c\udf5a", "cooked rice"],
        ["\ud83c\udf5b", "curry and rice"],
        ["\ud83c\udf5c", "steaming bowl"],
        ["\ud83c\udf5d", "spaghetti"],
        ["\ud83c\udf5e", "bread"],
        ["\ud83c\udf5f", "french fries"],
        ["\ud83c\udf60", "roasted sweet potato"],
        ["\ud83c\udf61", "dango"],
        ["\ud83c\udf62", "oden"],
        ["\ud83c\udf63", "sushi"],
        ["\ud83c\udf64", "fried shrimp"],
        ["\ud83c\udf65", "fish cake with swirl design"],
        ["\ud83c\udf66", "soft ice cream"],
        ["\ud83c\udf67", "shaved ice"],
        ["\ud83c\udf68", "ice cream"],
        ["\ud83c\udf69", "doughnut"],
        ["\ud83c\udf6a", "cookie"],
        ["\ud83c\udf6b", "chocolate bar"],
        ["\ud83c\udf6c", "candy"],
        ["\ud83c\udf6d", "lollipop"],
        ["\ud83c\udf6e", "custard"],
        ["\ud83c\udf6f", "honey pot"],
        ["\ud83c\udf70", "shortcake"],
        ["\ud83c\udf71", "bento box"],
        ["\ud83c\udf72", "pot of food"],
        ["\ud83c\udf73", "cooking"],
        ["\ud83c\udf74", "fork and knife"],
        ["\ud83c\udf75", "teacup without handle"],
        ["\ud83c\udf76", "sake bottle and cup"],
        ["\ud83c\udf77", "wine glass"],
        ["\ud83c\udf78", "cocktail glass"],
        ["\ud83c\udf79", "tropical drink"],
        ["\ud83c\udf7a", "beer mug"],
        ["\ud83c\udf7b", "clinking beer mugs"],
        ["\ud83c\udf7c", "baby bottle"],
        ["\ud83c\udf7d", "fork and knife with plate"],
        ["\ud83c\udf7e", "bottle with popping cork"],
        ["\ud83c\udf7f", "popcorn"],
        ["\ud83c\udf80", "ribbon"],
        ["\ud83c\udf81", "wrapped present"],
        ["\ud83c\udf82", "birthday cake"],
        ["\ud83c\udf83", "jack-o-lantern"],
        ["\ud83c\udf84", "christmas tree"],
        ["\ud83c\udf85", "father christmas"],
        ["\ud83c\udf86", "fireworks"],
        ["\ud83c\udf87", "firework sparkler"],
        ["\ud83c\udf88", "balloon"],
        ["\ud83c\udf89", "party popper"],
        ["\ud83c\udf8a", "confetti ball"],
        ["\ud83c\udf8b", "tanabata tree"],
        ["\ud83c\udf8c", "crossed flags"],
        ["\ud83c\udf8d", "pine decoration"],
        ["\ud83c\udf8e", "japanese dolls"],
        ["\ud83c\udf8f", "carp streamer"],
        ["\ud83c\udf90", "wind chime"],
        ["\ud83c\udf91", "moon viewing ceremony"],
        ["\ud83c\udf92", "school satchel"],
        ["\ud83c\udf93", "graduation cap"],
        ["\ud83c\udf94", "heart with tip on the left"],
        ["\ud83c\udf95", "bouquet of flowers"],
        ["\ud83c\udf96", "military medal"],
        ["\ud83c\udf97", "reminder ribbon"],
        ["\ud83c\udf98", "musical keyboard with jacks"],
        ["\ud83c\udf99", "studio microphone"],
        ["\ud83c\udf9a", "level slider"],
        ["\ud83c\udf9b", "control knobs"],
        ["\ud83c\udf9c", "beamed ascending musical notes"],
        ["\ud83c\udf9d", "beamed descending musical notes"],
        ["\ud83c\udf9e", "film frames"],
        ["\ud83c\udf9f", "admission tickets"],
        ["\ud83c\udfa0", "carousel horse"],
        ["\ud83c\udfa1", "ferris wheel"],
        ["\ud83c\udfa2", "roller coaster"],
        ["\ud83c\udfa3", "fishing pole and fish"],
        ["\ud83c\udfa4", "microphone"],
        ["\ud83c\udfa5", "movie camera"],
        ["\ud83c\udfa6", "cinema"],
        ["\ud83c\udfa7", "headphone"],
        ["\ud83c\udfa8", "artist palette"],
        ["\ud83c\udfa9", "top hat"],
        ["\ud83c\udfaa", "circus tent"],
        ["\ud83c\udfab", "ticket"],
        ["\ud83c\udfac", "clapper board"],
        ["\ud83c\udfad", "performing arts"],
        ["\ud83c\udfae", "video game"],
        ["\ud83c\udfaf", "direct hit"],
        ["\ud83c\udfb0", "slot machine"],
        ["\ud83c\udfb1", "billiards"],
        ["\ud83c\udfb2", "game die"],
        ["\ud83c\udfb3", "bowling"],
        ["\ud83c\udfb4", "flower playing cards"],
        ["\ud83c\udfb5", "musical note"],
        ["\ud83c\udfb6", "multiple musical notes"],
        ["\ud83c\udfb7", "saxophone"],
        ["\ud83c\udfb8", "guitar"],
        ["\ud83c\udfb9", "musical keyboard"],
        ["\ud83c\udfba", "trumpet"],
        ["\ud83c\udfbb", "violin"],
        ["\ud83c\udfbc", "musical score"],
        ["\ud83c\udfbd", "running shirt with sash"],
        ["\ud83c\udfbe", "tennis racquet and ball"],
        ["\ud83c\udfbf", "ski and ski boot"],
        ["\ud83c\udfc0", "basketball and hoop"],
        ["\ud83c\udfc1", "chequered flag"],
        ["\ud83c\udfc2", "snowboarder"],
        ["\ud83c\udfc3", "runner"],
        ["\ud83c\udfc4", "surfer"],
        ["\ud83c\udfc5", "sports medal"],
        ["\ud83c\udfc6", "trophy"],
        ["\ud83c\udfc7", "horse racing"],
        ["\ud83c\udfc8", "american football"],
        ["\ud83c\udfc9", "rugby football"],
        ["\ud83c\udfca", "swimmer"],
        ["\ud83c\udfcb", "weight lifter"],
        ["\ud83c\udfcc", "golfer"],
        ["\ud83c\udfcd", "racing motorcycle"],
        ["\ud83c\udfce", "racing car"],
        ["\ud83c\udfcf", "cricket bat and ball"],
        ["\ud83c\udfd0", "volleyball"],
        ["\ud83c\udfd1", "field hockey stick and ball"],
        ["\ud83c\udfd2", "ice hockey stick and puck"],
        ["\ud83c\udfd3", "table tennis paddle and ball"],
        ["\ud83c\udfd4", "snow capped mountain"],
        ["\ud83c\udfd5", "camping"],
        ["\ud83c\udfd6", "beach with umbrella"],
        ["\ud83c\udfd7", "building construction"],
        ["\ud83c\udfd8", "house buildings"],
        ["\ud83c\udfd9", "cityscape"],
        ["\ud83c\udfda", "derelict house building"],
        ["\ud83c\udfdb", "classical building"],
        ["\ud83c\udfdc", "desert"],
        ["\ud83c\udfdd", "desert island"],
        ["\ud83c\udfde", "national park"],
        ["\ud83c\udfdf", "stadium"],
        ["\ud83c\udfe0", "house building"],
        ["\ud83c\udfe1", "house with garden"],
        ["\ud83c\udfe2", "office building"],
        ["\ud83c\udfe3", "japanese post office"],
        ["\ud83c\udfe4", "european post office"],
        ["\ud83c\udfe5", "hospital"],
        ["\ud83c\udfe6", "bank"],
        ["\ud83c\udfe7", "automated teller machine"],
        ["\ud83c\udfe8", "hotel"],
        ["\ud83c\udfe9", "love hotel"],
        ["\ud83c\udfea", "convenience store"],
        ["\ud83c\udfeb", "school"],
        ["\ud83c\udfec", "department store"],
        ["\ud83c\udfed", "factory"],
        ["\ud83c\udfee", "izakaya lantern"],
        ["\ud83c\udfef", "japanese castle"],
        ["\ud83c\udff0", "european castle"],
        ["\ud83c\udff1", "white pennant"],
        ["\ud83c\udff2", "black pennant"],
        ["\ud83c\udff3", "waving white flag"],
        ["\ud83c\udff4", "waving black flag"],
        ["\ud83c\udff5", "rosette"],
        ["\ud83c\udff6", "black rosette"],
        ["\ud83c\udff7", "label"],
        ["\ud83c\udff8", "badminton racquet and shuttlecock"],
        ["\ud83c\udff9", "bow and arrow"],
        ["\ud83c\udffa", "amphora"],
        ["\ud83d\udc00", "rat"],
        ["\ud83d\udc01", "mouse"],
        ["\ud83d\udc02", "ox"],
        ["\ud83d\udc03", "water buffalo"],
        ["\ud83d\udc04", "cow"],
        ["\ud83d\udc05", "tiger"],
        ["\ud83d\udc06", "leopard"],
        ["\ud83d\udc07", "rabbit"],
        ["\ud83d\udc08", "cat"],
        ["\ud83d\udc09", "dragon"],
        ["\ud83d\udc0a", "crocodile"],
        ["\ud83d\udc0b", "whale"],
        ["\ud83d\udc0c", "snail"],
        ["\ud83d\udc0d", "snake"],
        ["\ud83d\udc0e", "horse"],
        ["\ud83d\udc0f", "ram"],
        ["\ud83d\udc10", "goat"],
        ["\ud83d\udc11", "sheep"],
        ["\ud83d\udc12", "monkey"],
        ["\ud83d\udc13", "rooster"],
        ["\ud83d\udc14", "chicken"],
        ["\ud83d\udc15", "dog"],
        ["\ud83d\udc16", "pig"],
        ["\ud83d\udc17", "boar"],
        ["\ud83d\udc18", "elephant"],
        ["\ud83d\udc19", "octopus"],
        ["\ud83d\udc1a", "spiral shell"],
        ["\ud83d\udc1b", "bug"],
        ["\ud83d\udc1c", "ant"],
        ["\ud83d\udc1d", "honeybee"],
        ["\ud83d\udc1e", "lady beetle"],
        ["\ud83d\udc1f", "fish"],
        ["\ud83d\udc20", "tropical fish"],
        ["\ud83d\udc21", "blowfish"],
        ["\ud83d\udc22", "turtle"],
        ["\ud83d\udc23", "hatching chick"],
        ["\ud83d\udc24", "baby chick"],
        ["\ud83d\udc25", "front-facing baby chick"],
        ["\ud83d\udc26", "bird"],
        ["\ud83d\udc27", "penguin"],
        ["\ud83d\udc28", "koala"],
        ["\ud83d\udc29", "poodle"],
        ["\ud83d\udc2a", "dromedary camel"],
        ["\ud83d\udc2b", "bactrian camel"],
        ["\ud83d\udc2c", "dolphin"],
        ["\ud83d\udc2d", "mouse face"],
        ["\ud83d\udc2e", "cow face"],
        ["\ud83d\udc2f", "tiger face"],
        ["\ud83d\udc30", "rabbit face"],
        ["\ud83d\udc31", "cat face"],
        ["\ud83d\udc32", "dragon face"],
        ["\ud83d\udc33", "spouting whale"],
        ["\ud83d\udc34", "horse face"],
        ["\ud83d\udc35", "monkey face"],
        ["\ud83d\udc36", "dog face"],
        ["\ud83d\udc37", "pig face"],
        ["\ud83d\udc38", "frog face"],
        ["\ud83d\udc39", "hamster face"],
        ["\ud83d\udc3a", "wolf face"],
        ["\ud83d\udc3b", "bear face"],
        ["\ud83d\udc3c", "panda face"],
        ["\ud83d\udc3d", "pig nose"],
        ["\ud83d\udc3e", "paw prints"],
        ["\ud83d\udc3f", "chipmunk"],
        ["\ud83d\udc40", "eyes"],
        ["\ud83d\udc41", "eye"],
        ["\ud83d\udc42", "ear"],
        ["\ud83d\udc43", "nose"],
        ["\ud83d\udc44", "mouth"],
        ["\ud83d\udc45", "tongue"],
        ["\ud83d\udc46", "white up pointing backhand index"],
        ["\ud83d\udc47", "white down pointing backhand index"],
        ["\ud83d\udc48", "white left pointing backhand index"],
        ["\ud83d\udc49", "white right pointing backhand index"],
        ["\ud83d\udc4a", "fisted hand sign"],
        ["\ud83d\udc4b", "waving hand sign"],
        ["\ud83d\udc4c", "ok hand sign"],
        ["\ud83d\udc4d", "thumbs up sign"],
        ["\ud83d\udc4e", "thumbs down sign"],
        ["\ud83d\udc4f", "clapping hands sign"],
        ["\ud83d\udc50", "open hands sign"],
        ["\ud83d\udc51", "crown"],
        ["\ud83d\udc52", "womans hat"],
        ["\ud83d\udc53", "eyeglasses"],
        ["\ud83d\udc54", "necktie"],
        ["\ud83d\udc55", "t-shirt"],
        ["\ud83d\udc56", "jeans"],
        ["\ud83d\udc57", "dress"],
        ["\ud83d\udc58", "kimono"],
        ["\ud83d\udc59", "bikini"],
        ["\ud83d\udc5a", "womans clothes"],
        ["\ud83d\udc5b", "purse"],
        ["\ud83d\udc5c", "handbag"],
        ["\ud83d\udc5d", "pouch"],
        ["\ud83d\udc5e", "mans shoe"],
        ["\ud83d\udc5f", "athletic shoe"],
        ["\ud83d\udc60", "high-heeled shoe"],
        ["\ud83d\udc61", "womans sandal"],
        ["\ud83d\udc62", "womans boots"],
        ["\ud83d\udc63", "footprints"],
        ["\ud83d\udc64", "bust in silhouette"],
        ["\ud83d\udc65", "busts in silhouette"],
        ["\ud83d\udc66", "boy"],
        ["\ud83d\udc67", "girl"],
        ["\ud83d\udc68", "man"],
        ["\ud83d\udc69", "woman"],
        ["\ud83d\udc6a", "family"],
        ["\ud83d\udc6b", "man and woman holding hands"],
        ["\ud83d\udc6c", "two men holding hands"],
        ["\ud83d\udc6d", "two women holding hands"],
        ["\ud83d\udc6e", "police officer"],
        ["\ud83d\udc6f", "woman with bunny ears"],
        ["\ud83d\udc70", "bride with veil"],
        ["\ud83d\udc71", "person with blond hair"],
        ["\ud83d\udc72", "man with gua pi mao"],
        ["\ud83d\udc73", "man with turban"],
        ["\ud83d\udc74", "older man"],
        ["\ud83d\udc75", "older woman"],
        ["\ud83d\udc76", "baby"],
        ["\ud83d\udc77", "construction worker"],
        ["\ud83d\udc78", "princess"],
        ["\ud83d\udc79", "japanese ogre"],
        ["\ud83d\udc7a", "japanese goblin"],
        ["\ud83d\udc7b", "ghost"],
        ["\ud83d\udc7c", "baby angel"],
        ["\ud83d\udc7d", "extraterrestrial alien"],
        ["\ud83d\udc7e", "alien monster"],
        ["\ud83d\udc7f", "imp"],
        ["\ud83d\udc80", "skull"],
        ["\ud83d\udc81", "information desk person"],
        ["\ud83d\udc82", "guardsman"],
        ["\ud83d\udc83", "dancer"],
        ["\ud83d\udc84", "lipstick"],
        ["\ud83d\udc85", "nail polish"],
        ["\ud83d\udc86", "face massage"],
        ["\ud83d\udc87", "haircut"],
        ["\ud83d\udc88", "barber pole"],
        ["\ud83d\udc89", "syringe"],
        ["\ud83d\udc8a", "pill"],
        ["\ud83d\udc8b", "kiss mark"],
        ["\ud83d\udc8c", "love letter"],
        ["\ud83d\udc8d", "ring"],
        ["\ud83d\udc8e", "gem stone"],
        ["\ud83d\udc8f", "kiss"],
        ["\ud83d\udc90", "bouquet"],
        ["\ud83d\udc91", "couple with heart"],
        ["\ud83d\udc92", "wedding"],
        ["\ud83d\udc93", "beating heart"],
        ["\ud83d\udc94", "broken heart"],
        ["\ud83d\udc95", "two hearts"],
        ["\ud83d\udc96", "sparkling heart"],
        ["\ud83d\udc97", "growing heart"],
        ["\ud83d\udc98", "heart with arrow"],
        ["\ud83d\udc99", "blue heart"],
        ["\ud83d\udc9a", "green heart"],
        ["\ud83d\udc9b", "yellow heart"],
        ["\ud83d\udc9c", "purple heart"],
        ["\ud83d\udc9d", "heart with ribbon"],
        ["\ud83d\udc9e", "revolving hearts"],
        ["\ud83d\udc9f", "heart decoration"],
        ["\ud83d\udca0", "diamond shape with a dot inside"],
        ["\ud83d\udca1", "electric light bulb"],
        ["\ud83d\udca2", "anger symbol"],
        ["\ud83d\udca3", "bomb"],
        ["\ud83d\udca4", "sleeping symbol"],
        ["\ud83d\udca5", "collision symbol"],
        ["\ud83d\udca6", "splashing sweat symbol"],
        ["\ud83d\udca7", "droplet"],
        ["\ud83d\udca8", "dash symbol"],
        ["\ud83d\udca9", "pile of poo"],
        ["\ud83d\udcaa", "flexed biceps"],
        ["\ud83d\udcab", "dizzy symbol"],
        ["\ud83d\udcac", "speech balloon"],
        ["\ud83d\udcad", "thought balloon"],
        ["\ud83d\udcae", "white flower"],
        ["\ud83d\udcaf", "hundred points symbol"],
        ["\ud83d\udcb0", "money bag"],
        ["\ud83d\udcb1", "currency exchange"],
        ["\ud83d\udcb2", "heavy dollar sign"],
        ["\ud83d\udcb3", "credit card"],
        ["\ud83d\udcb4", "banknote with yen sign"],
        ["\ud83d\udcb5", "banknote with dollar sign"],
        ["\ud83d\udcb6", "banknote with euro sign"],
        ["\ud83d\udcb7", "banknote with pound sign"],
        ["\ud83d\udcb8", "money with wings"],
        ["\ud83d\udcb9", "chart with upwards trend and yen sign"],
        ["\ud83d\udcba", "seat"],
        ["\ud83d\udcbb", "personal computer"],
        ["\ud83d\udcbc", "briefcase"],
        ["\ud83d\udcbd", "minidisc"],
        ["\ud83d\udcbe", "floppy disk"],
        ["\ud83d\udcbf", "optical disc"],
        ["\ud83d\udcc0", "dvd"],
        ["\ud83d\udcc1", "file folder"],
        ["\ud83d\udcc2", "open file folder"],
        ["\ud83d\udcc3", "page with curl"],
        ["\ud83d\udcc4", "page facing up"],
        ["\ud83d\udcc5", "calendar"],
        ["\ud83d\udcc6", "tear-off calendar"],
        ["\ud83d\udcc7", "card index"],
        ["\ud83d\udcc8", "chart with upwards trend"],
        ["\ud83d\udcc9", "chart with downwards trend"],
        ["\ud83d\udcca", "bar chart"],
        ["\ud83d\udccb", "clipboard"],
        ["\ud83d\udccc", "pushpin"],
        ["\ud83d\udccd", "round pushpin"],
        ["\ud83d\udcce", "paperclip"],
        ["\ud83d\udccf", "straight ruler"],
        ["\ud83d\udcd0", "triangular ruler"],
        ["\ud83d\udcd1", "bookmark tabs"],
        ["\ud83d\udcd2", "ledger"],
        ["\ud83d\udcd3", "notebook"],
        ["\ud83d\udcd4", "notebook with decorative cover"],
        ["\ud83d\udcd5", "closed book"],
        ["\ud83d\udcd6", "open book"],
        ["\ud83d\udcd7", "green book"],
        ["\ud83d\udcd8", "blue book"],
        ["\ud83d\udcd9", "orange book"],
        ["\ud83d\udcda", "books"],
        ["\ud83d\udcdb", "name badge"],
        ["\ud83d\udcdc", "scroll"],
        ["\ud83d\udcdd", "memo"],
        ["\ud83d\udcde", "telephone receiver"],
        ["\ud83d\udcdf", "pager"],
        ["\ud83d\udce0", "fax machine"],
        ["\ud83d\udce1", "satellite antenna"],
        ["\ud83d\udce2", "public address loudspeaker"],
        ["\ud83d\udce3", "cheering megaphone"],
        ["\ud83d\udce4", "outbox tray"],
        ["\ud83d\udce5", "inbox tray"],
        ["\ud83d\udce6", "package"],
        ["\ud83d\udce7", "e-mail symbol"],
        ["\ud83d\udce8", "incoming envelope"],
        ["\ud83d\udce9", "envelope with downwards arrow above"],
        ["\ud83d\udcea", "closed mailbox with lowered flag"],
        ["\ud83d\udceb", "closed mailbox with raised flag"],
        ["\ud83d\udcec", "open mailbox with raised flag"],
        ["\ud83d\udced", "open mailbox with lowered flag"],
        ["\ud83d\udcee", "postbox"],
        ["\ud83d\udcef", "postal horn"],
        ["\ud83d\udcf0", "newspaper"],
        ["\ud83d\udcf1", "mobile phone"],
        ["\ud83d\udcf2", "mobile phone with rightwards arrow at left"],
        ["\ud83d\udcf3", "vibration mode"],
        ["\ud83d\udcf4", "mobile phone off"],
        ["\ud83d\udcf5", "no mobile phones"],
        ["\ud83d\udcf6", "antenna with bars"],
        ["\ud83d\udcf7", "camera"],
        ["\ud83d\udcf8", "camera with flash"],
        ["\ud83d\udcf9", "video camera"],
        ["\ud83d\udcfa", "television"],
        ["\ud83d\udcfb", "radio"],
        ["\ud83d\udcfc", "videocassette"],
        ["\ud83d\udcfd", "film projector"],
        ["\ud83d\udcfe", "portable stereo"],
        ["\ud83d\udcff", "prayer beads"],
        ["\ud83d\udd00", "twisted rightwards arrows"],
        ["\ud83d\udd01", "clockwise rightwards and leftwards open circle arrows"],
        ["\ud83d\udd02", "clockwise rightwards and leftwards open circle arrows with circled one overlay"],
        ["\ud83d\udd03", "clockwise downwards and upwards open circle arrows"],
        ["\ud83d\udd04", "anticlockwise downwards and upwards open circle arrows"],
        ["\ud83d\udd05", "low brightness symbol"],
        ["\ud83d\udd06", "high brightness symbol"],
        ["\ud83d\udd07", "speaker with cancellation stroke"],
        ["\ud83d\udd08", "speaker"],
        ["\ud83d\udd09", "speaker with one sound wave"],
        ["\ud83d\udd0a", "speaker with three sound waves"],
        ["\ud83d\udd0b", "battery"],
        ["\ud83d\udd0c", "electric plug"],
        ["\ud83d\udd0d", "left-pointing magnifying glass"],
        ["\ud83d\udd0e", "right-pointing magnifying glass"],
        ["\ud83d\udd0f", "lock with ink pen"],
        ["\ud83d\udd10", "closed lock with key"],
        ["\ud83d\udd11", "key"],
        ["\ud83d\udd12", "lock"],
        ["\ud83d\udd13", "open lock"],
        ["\ud83d\udd14", "bell"],
        ["\ud83d\udd15", "bell with cancellation stroke"],
        ["\ud83d\udd16", "bookmark"],
        ["\ud83d\udd17", "link symbol"],
        ["\ud83d\udd18", "radio button"],
        ["\ud83d\udd19", "back with leftwards arrow above"],
        ["\ud83d\udd1a", "end with leftwards arrow above"],
        ["\ud83d\udd1b", "on with exclamation mark with left right arrow above"],
        ["\ud83d\udd1c", "soon with rightwards arrow above"],
        ["\ud83d\udd1d", "top with upwards arrow above"],
        ["\ud83d\udd1e", "no one under eighteen symbol"],
        ["\ud83d\udd1f", "keycap ten"],
        ["\ud83d\udd20", "input symbol for latin capital letters"],
        ["\ud83d\udd21", "input symbol for latin small letters"],
        ["\ud83d\udd22", "input symbol for numbers"],
        ["\ud83d\udd23", "input symbol for symbols"],
        ["\ud83d\udd24", "input symbol for latin letters"],
        ["\ud83d\udd25", "fire"],
        ["\ud83d\udd26", "electric torch"],
        ["\ud83d\udd27", "wrench"],
        ["\ud83d\udd28", "hammer"],
        ["\ud83d\udd29", "nut and bolt"],
        ["\ud83d\udd2a", "hocho"],
        ["\ud83d\udd2b", "pistol"],
        ["\ud83d\udd2c", "microscope"],
        ["\ud83d\udd2d", "telescope"],
        ["\ud83d\udd2e", "crystal ball"],
        ["\ud83d\udd2f", "six pointed star with middle dot"],
        ["\ud83d\udd30", "japanese symbol for beginner"],
        ["\ud83d\udd31", "trident emblem"],
        ["\ud83d\udd32", "black square button"],
        ["\ud83d\udd33", "white square button"],
        ["\ud83d\udd34", "large red circle"],
        ["\ud83d\udd35", "large blue circle"],
        ["\ud83d\udd36", "large orange diamond"],
        ["\ud83d\udd37", "large blue diamond"],
        ["\ud83d\udd38", "small orange diamond"],
        ["\ud83d\udd39", "small blue diamond"],
        ["\ud83d\udd3a", "up-pointing red triangle"],
        ["\ud83d\udd3b", "down-pointing red triangle"],
        ["\ud83d\udd3c", "up-pointing small red triangle"],
        ["\ud83d\udd3d", "down-pointing small red triangle"],
        ["\ud83d\udd3e", "lower right shadowed white circle"],
        ["\ud83d\udd3f", "upper right shadowed white circle"],
        ["\ud83d\udd40", "circled cross pommee"],
        ["\ud83d\udd41", "cross pommee with half-circle below"],
        ["\ud83d\udd42", "cross pommee"],
        ["\ud83d\udd43", "notched left semicircle with three dots"],
        ["\ud83d\udd44", "notched right semicircle with three dots"],
        ["\ud83d\udd45", "symbol for marks chapter"],
        ["\ud83d\udd46", "white latin cross"],
        ["\ud83d\udd47", "heavy latin cross"],
        ["\ud83d\udd48", "celtic cross"],
        ["\ud83d\udd49", "om symbol"],
        ["\ud83d\udd4a", "dove of peace"],
        ["\ud83d\udd4b", "kaaba"],
        ["\ud83d\udd4c", "mosque"],
        ["\ud83d\udd4d", "synagogue"],
        ["\ud83d\udd4e", "menorah with nine branches"],
        ["\ud83d\udd4f", "bowl of hygieia"],
        ["\ud83d\udd50", "clock face one oclock"],
        ["\ud83d\udd51", "clock face two oclock"],
        ["\ud83d\udd52", "clock face three oclock"],
        ["\ud83d\udd53", "clock face four oclock"],
        ["\ud83d\udd54", "clock face five oclock"],
        ["\ud83d\udd55", "clock face six oclock"],
        ["\ud83d\udd56", "clock face seven oclock"],
        ["\ud83d\udd57", "clock face eight oclock"],
        ["\ud83d\udd58", "clock face nine oclock"],
        ["\ud83d\udd59", "clock face ten oclock"],
        ["\ud83d\udd5a", "clock face eleven oclock"],
        ["\ud83d\udd5b", "clock face twelve oclock"],
        ["\ud83d\udd5c", "clock face one-thirty"],
        ["\ud83d\udd5d", "clock face two-thirty"],
        ["\ud83d\udd5e", "clock face three-thirty"],
        ["\ud83d\udd5f", "clock face four-thirty"],
        ["\ud83d\udd60", "clock face five-thirty"],
        ["\ud83d\udd61", "clock face six-thirty"],
        ["\ud83d\udd62", "clock face seven-thirty"],
        ["\ud83d\udd63", "clock face eight-thirty"],
        ["\ud83d\udd64", "clock face nine-thirty"],
        ["\ud83d\udd65", "clock face ten-thirty"],
        ["\ud83d\udd66", "clock face eleven-thirty"],
        ["\ud83d\udd67", "clock face twelve-thirty"],
        ["\ud83d\udd68", "right speaker"],
        ["\ud83d\udd69", "right speaker with one sound wave"],
        ["\ud83d\udd6a", "right speaker with three sound waves"],
        ["\ud83d\udd6b", "bullhorn"],
        ["\ud83d\udd6c", "bullhorn with sound waves"],
        ["\ud83d\udd6d", "ringing bell"],
        ["\ud83d\udd6e", "book"],
        ["\ud83d\udd6f", "candle"],
        ["\ud83d\udd70", "mantelpiece clock"],
        ["\ud83d\udd71", "black skull and crossbones"],
        ["\ud83d\udd72", "no piracy"],
        ["\ud83d\udd73", "hole"],
        ["\ud83d\udd74", "man in business suit levitating"],
        ["\ud83d\udd75", "sleuth or spy"],
        ["\ud83d\udd76", "dark sunglasses"],
        ["\ud83d\udd77", "spider"],
        ["\ud83d\udd78", "spider web"],
        ["\ud83d\udd79", "joystick"],
        ["\ud83d\udd7a", "man dancing"],
        ["\ud83d\udd7b", "left hand telephone receiver"],
        ["\ud83d\udd7c", "telephone receiver with page"],
        ["\ud83d\udd7d", "right hand telephone receiver"],
        ["\ud83d\udd7e", "white touchtone telephone"],
        ["\ud83d\udd7f", "black touchtone telephone"],
        ["\ud83d\udd80", "telephone on top of modem"],
        ["\ud83d\udd81", "clamshell mobile phone"],
        ["\ud83d\udd82", "back of envelope"],
        ["\ud83d\udd83", "stamped envelope"],
        ["\ud83d\udd84", "envelope with lightning"],
        ["\ud83d\udd85", "flying envelope"],
        ["\ud83d\udd86", "pen over stamped envelope"],
        ["\ud83d\udd87", "linked paperclips"],
        ["\ud83d\udd88", "black pushpin"],
        ["\ud83d\udd89", "lower left pencil"],
        ["\ud83d\udd8a", "lower left ballpoint pen"],
        ["\ud83d\udd8b", "lower left fountain pen"],
        ["\ud83d\udd8c", "lower left paintbrush"],
        ["\ud83d\udd8d", "lower left crayon"],
        ["\ud83d\udd8e", "left writing hand"],
        ["\ud83d\udd8f", "turned ok hand sign"],
        ["\ud83d\udd90", "raised hand with fingers splayed"],
        ["\ud83d\udd91", "reversed raised hand with fingers splayed"],
        ["\ud83d\udd92", "reversed thumbs up sign"],
        ["\ud83d\udd93", "reversed thumbs down sign"],
        ["\ud83d\udd94", "reversed victory hand"],
        ["\ud83d\udd95", "reversed hand with middle finger extended"],
        ["\ud83d\udd96", "raised hand with part between middle and ring fingers"],
        ["\ud83d\udd97", "white down pointing left hand index"],
        ["\ud83d\udd98", "sideways white left pointing index"],
        ["\ud83d\udd99", "sideways white right pointing index"],
        ["\ud83d\udd9a", "sideways black left pointing index"],
        ["\ud83d\udd9b", "sideways black right pointing index"],
        ["\ud83d\udd9c", "black left pointing backhand index"],
        ["\ud83d\udd9d", "black right pointing backhand index"],
        ["\ud83d\udd9e", "sideways white up pointing index"],
        ["\ud83d\udd9f", "sideways white down pointing index"],
        ["\ud83d\udda0", "sideways black up pointing index"],
        ["\ud83d\udda1", "sideways black down pointing index"],
        ["\ud83d\udda2", "black up pointing backhand index"],
        ["\ud83d\udda3", "black down pointing backhand index"],
        ["\ud83d\udda4", "black heart"],
        ["\ud83d\udda5", "desktop computer"],
        ["\ud83d\udda6", "keyboard and mouse"],
        ["\ud83d\udda7", "three networked computers"],
        ["\ud83d\udda8", "printer"],
        ["\ud83d\udda9", "pocket calculator"],
        ["\ud83d\uddaa", "black hard shell floppy disk"],
        ["\ud83d\uddab", "white hard shell floppy disk"],
        ["\ud83d\uddac", "soft shell floppy disk"],
        ["\ud83d\uddad", "tape cartridge"],
        ["\ud83d\uddae", "wired keyboard"],
        ["\ud83d\uddaf", "one button mouse"],
        ["\ud83d\uddb0", "two button mouse"],
        ["\ud83d\uddb1", "three button mouse"],
        ["\ud83d\uddb2", "trackball"],
        ["\ud83d\uddb3", "old personal computer"],
        ["\ud83d\uddb4", "hard disk"],
        ["\ud83d\uddb5", "screen"],
        ["\ud83d\uddb6", "printer icon"],
        ["\ud83d\uddb7", "fax icon"],
        ["\ud83d\uddb8", "optical disc icon"],
        ["\ud83d\uddb9", "document with text"],
        ["\ud83d\uddba", "document with text and picture"],
        ["\ud83d\uddbb", "document with picture"],
        ["\ud83d\uddbc", "frame with picture"],
        ["\ud83d\uddbd", "frame with tiles"],
        ["\ud83d\uddbe", "frame with an x"],
        ["\ud83d\uddbf", "black folder"],
        ["\ud83d\uddc0", "folder"],
        ["\ud83d\uddc1", "open folder"],
        ["\ud83d\uddc2", "card index dividers"],
        ["\ud83d\uddc3", "card file box"],
        ["\ud83d\uddc4", "file cabinet"],
        ["\ud83d\uddc5", "empty note"],
        ["\ud83d\uddc6", "empty note page"],
        ["\ud83d\uddc7", "empty note pad"],
        ["\ud83d\uddc8", "note"],
        ["\ud83d\uddc9", "note page"],
        ["\ud83d\uddca", "note pad"],
        ["\ud83d\uddcb", "empty document"],
        ["\ud83d\uddcc", "empty page"],
        ["\ud83d\uddcd", "empty pages"],
        ["\ud83d\uddce", "document"],
        ["\ud83d\uddcf", "page"],
        ["\ud83d\uddd0", "pages"],
        ["\ud83d\uddd1", "wastebasket"],
        ["\ud83d\uddd2", "spiral note pad"],
        ["\ud83d\uddd3", "spiral calendar pad"],
        ["\ud83d\uddd4", "desktop window"],
        ["\ud83d\uddd5", "minimize"],
        ["\ud83d\uddd6", "maximize"],
        ["\ud83d\uddd7", "overlap"],
        ["\ud83d\uddd8", "clockwise right and left semicircle arrows"],
        ["\ud83d\uddd9", "cancellation x"],
        ["\ud83d\uddda", "increase font size symbol"],
        ["\ud83d\udddb", "decrease font size symbol"],
        ["\ud83d\udddc", "compression"],
        ["\ud83d\udddd", "old key"],
        ["\ud83d\uddde", "rolled-up newspaper"],
        ["\ud83d\udddf", "page with circled text"],
        ["\ud83d\udde0", "stock chart"],
        ["\ud83d\udde1", "dagger knife"],
        ["\ud83d\udde2", "lips"],
        ["\ud83d\udde3", "speaking head in silhouette"],
        ["\ud83d\udde4", "three rays above"],
        ["\ud83d\udde5", "three rays below"],
        ["\ud83d\udde6", "three rays left"],
        ["\ud83d\udde7", "three rays right"],
        ["\ud83d\udde8", "left speech bubble"],
        ["\ud83d\udde9", "right speech bubble"],
        ["\ud83d\uddea", "two speech bubbles"],
        ["\ud83d\uddeb", "three speech bubbles"],
        ["\ud83d\uddec", "left thought bubble"],
        ["\ud83d\udded", "right thought bubble"],
        ["\ud83d\uddee", "left anger bubble"],
        ["\ud83d\uddef", "right anger bubble"],
        ["\ud83d\uddf0", "mood bubble"],
        ["\ud83d\uddf1", "lightning mood bubble"],
        ["\ud83d\uddf2", "lightning mood"],
        ["\ud83d\uddf3", "ballot box with ballot"],
        ["\ud83d\uddf4", "ballot script x"],
        ["\ud83d\uddf5", "ballot box with script x"],
        ["\ud83d\uddf6", "ballot bold script x"],
        ["\ud83d\uddf7", "ballot box with bold script x"],
        ["\ud83d\uddf8", "light check mark"],
        ["\ud83d\uddf9", "ballot box with bold check"],
        ["\ud83d\uddfa", "world map"],
        ["\ud83d\uddfb", "mount fuji"],
        ["\ud83d\uddfc", "tokyo tower"],
        ["\ud83d\uddfd", "statue of liberty"],
        ["\ud83d\uddfe", "silhouette of japan"],
        ["\ud83d\uddff", "moyai"],
        ["\ud83d\ude00", "grinning face"],
        ["\ud83d\ude01", "grinning face with smiling eyes"],
        ["\ud83d\ude02", "face with tears of joy"],
        ["\ud83d\ude03", "smiling face with open mouth"],
        ["\ud83d\ude04", "smiling face with open mouth and smiling eyes"],
        ["\ud83d\ude05", "smiling face with open mouth and cold sweat"],
        ["\ud83d\ude06", "smiling face with open mouth and tightly-closed eyes"],
        ["\ud83d\ude07", "smiling face with halo"],
        ["\ud83d\ude08", "smiling face with horns"],
        ["\ud83d\ude09", "winking face"],
        ["\ud83d\ude0a", "smiling face with smiling eyes"],
        ["\ud83d\ude0b", "face savouring delicious food"],
        ["\ud83d\ude0c", "relieved face"],
        ["\ud83d\ude0d", "smiling face with heart-shaped eyes"],
        ["\ud83d\ude0e", "smiling face with sunglasses"],
        ["\ud83d\ude0f", "smirking face"],
        ["\ud83d\ude10", "neutral face"],
        ["\ud83d\ude11", "expressionless face"],
        ["\ud83d\ude12", "unamused face"],
        ["\ud83d\ude13", "face with cold sweat"],
        ["\ud83d\ude14", "pensive face"],
        ["\ud83d\ude15", "confused face"],
        ["\ud83d\ude16", "confounded face"],
        ["\ud83d\ude17", "kissing face"],
        ["\ud83d\ude18", "face throwing a kiss"],
        ["\ud83d\ude19", "kissing face with smiling eyes"],
        ["\ud83d\ude1a", "kissing face with closed eyes"],
        ["\ud83d\ude1b", "face with stuck-out tongue"],
        ["\ud83d\ude1c", "face with stuck-out tongue and winking eye"],
        ["\ud83d\ude1d", "face with stuck-out tongue and tightly-closed eyes"],
        ["\ud83d\ude1e", "disappointed face"],
        ["\ud83d\ude1f", "worried face"],
        ["\ud83d\ude20", "angry face"],
        ["\ud83d\ude21", "pouting face"],
        ["\ud83d\ude22", "crying face"],
        ["\ud83d\ude23", "persevering face"],
        ["\ud83d\ude24", "face with look of triumph"],
        ["\ud83d\ude25", "disappointed but relieved face"],
        ["\ud83d\ude26", "frowning face with open mouth"],
        ["\ud83d\ude27", "anguished face"],
        ["\ud83d\ude28", "fearful face"],
        ["\ud83d\ude29", "weary face"],
        ["\ud83d\ude2a", "sleepy face"],
        ["\ud83d\ude2b", "tired face"],
        ["\ud83d\ude2c", "grimacing face"],
        ["\ud83d\ude2d", "loudly crying face"],
        ["\ud83d\ude2e", "face with open mouth"],
        ["\ud83d\ude2f", "hushed face"],
        ["\ud83d\ude30", "face with open mouth and cold sweat"],
        ["\ud83d\ude31", "face screaming in fear"],
        ["\ud83d\ude32", "astonished face"],
        ["\ud83d\ude33", "flushed face"],
        ["\ud83d\ude34", "sleeping face"],
        ["\ud83d\ude35", "dizzy face"],
        ["\ud83d\ude36", "face without mouth"],
        ["\ud83d\ude37", "face with medical mask"],
        ["\ud83d\ude38", "grinning cat face with smiling eyes"],
        ["\ud83d\ude39", "cat face with tears of joy"],
        ["\ud83d\ude3a", "smiling cat face with open mouth"],
        ["\ud83d\ude3b", "smiling cat face with heart-shaped eyes"],
        ["\ud83d\ude3c", "cat face with wry smile"],
        ["\ud83d\ude3d", "kissing cat face with closed eyes"],
        ["\ud83d\ude3e", "pouting cat face"],
        ["\ud83d\ude3f", "crying cat face"],
        ["\ud83d\ude40", "weary cat face"],
        ["\ud83d\ude41", "slightly frowning face"],
        ["\ud83d\ude42", "slightly smiling face"],
        ["\ud83d\ude43", "upside-down face"],
        ["\ud83d\ude44", "face with rolling eyes"],
        ["\ud83d\ude45", "face with no good gesture"],
        ["\ud83d\ude46", "face with ok gesture"],
        ["\ud83d\ude47", "person bowing deeply"],
        ["\ud83d\ude48", "see-no-evil monkey"],
        ["\ud83d\ude49", "hear-no-evil monkey"],
        ["\ud83d\ude4a", "speak-no-evil monkey"],
        ["\ud83d\ude4b", "happy person raising one hand"],
        ["\ud83d\ude4c", "person raising both hands in celebration"],
        ["\ud83d\ude4d", "person frowning"],
        ["\ud83d\ude4e", "person with pouting face"],
        ["\ud83d\ude4f", "person with folded hands"],
        ["\ud83d\ude80", "rocket"],
        ["\ud83d\ude81", "helicopter"],
        ["\ud83d\ude82", "steam locomotive"],
        ["\ud83d\ude83", "railway car"],
        ["\ud83d\ude84", "high-speed train"],
        ["\ud83d\ude85", "high-speed train with bullet nose"],
        ["\ud83d\ude86", "train"],
        ["\ud83d\ude87", "metro"],
        ["\ud83d\ude88", "light rail"],
        ["\ud83d\ude89", "station"],
        ["\ud83d\ude8a", "tram"],
        ["\ud83d\ude8b", "tram car"],
        ["\ud83d\ude8c", "bus"],
        ["\ud83d\ude8d", "oncoming bus"],
        ["\ud83d\ude8e", "trolleybus"],
        ["\ud83d\ude8f", "bus stop"],
        ["\ud83d\ude90", "minibus"],
        ["\ud83d\ude91", "ambulance"],
        ["\ud83d\ude92", "fire engine"],
        ["\ud83d\ude93", "police car"],
        ["\ud83d\ude94", "oncoming police car"],
        ["\ud83d\ude95", "taxi"],
        ["\ud83d\ude96", "oncoming taxi"],
        ["\ud83d\ude97", "automobile"],
        ["\ud83d\ude98", "oncoming automobile"],
        ["\ud83d\ude99", "recreational vehicle"],
        ["\ud83d\ude9a", "delivery truck"],
        ["\ud83d\ude9b", "articulated lorry"],
        ["\ud83d\ude9c", "tractor"],
        ["\ud83d\ude9d", "monorail"],
        ["\ud83d\ude9e", "mountain railway"],
        ["\ud83d\ude9f", "suspension railway"],
        ["\ud83d\udea0", "mountain cableway"],
        ["\ud83d\udea1", "aerial tramway"],
        ["\ud83d\udea2", "ship"],
        ["\ud83d\udea3", "rowboat"],
        ["\ud83d\udea4", "speedboat"],
        ["\ud83d\udea5", "horizontal traffic light"],
        ["\ud83d\udea6", "vertical traffic light"],
        ["\ud83d\udea7", "construction sign"],
        ["\ud83d\udea8", "police cars revolving light"],
        ["\ud83d\udea9", "triangular flag on post"],
        ["\ud83d\udeaa", "door"],
        ["\ud83d\udeab", "no entry sign"],
        ["\ud83d\udeac", "smoking symbol"],
        ["\ud83d\udead", "no smoking symbol"],
        ["\ud83d\udeae", "put litter in its place symbol"],
        ["\ud83d\udeaf", "do not litter symbol"],
        ["\ud83d\udeb0", "potable water symbol"],
        ["\ud83d\udeb1", "non-potable water symbol"],
        ["\ud83d\udeb2", "bicycle"],
        ["\ud83d\udeb3", "no bicycles"],
        ["\ud83d\udeb4", "bicyclist"],
        ["\ud83d\udeb5", "mountain bicyclist"],
        ["\ud83d\udeb6", "pedestrian"],
        ["\ud83d\udeb7", "no pedestrians"],
        ["\ud83d\udeb8", "children crossing"],
        ["\ud83d\udeb9", "mens symbol"],
        ["\ud83d\udeba", "womens symbol"],
        ["\ud83d\udebb", "restroom"],
        ["\ud83d\udebc", "baby symbol"],
        ["\ud83d\udebd", "toilet"],
        ["\ud83d\udebe", "water closet"],
        ["\ud83d\udebf", "shower"],
        ["\ud83d\udec0", "bath"],
        ["\ud83d\udec1", "bathtub"],
        ["\ud83d\udec2", "passport control"],
        ["\ud83d\udec3", "customs"],
        ["\ud83d\udec4", "baggage claim"],
        ["\ud83d\udec5", "left luggage"],
        ["\ud83d\udec6", "triangle with rounded corners"],
        ["\ud83d\udec7", "prohibited sign"],
        ["\ud83d\udec8", "circled information source"],
        ["\ud83d\udec9", "boys symbol"],
        ["\ud83d\udeca", "girls symbol"],
        ["\ud83d\udecb", "couch and lamp"],
        ["\ud83d\udecc", "sleeping accommodation"],
        ["\ud83d\udecd", "shopping bags"],
        ["\ud83d\udece", "bellhop bell"],
        ["\ud83d\udecf", "bed"],
        ["\ud83d\uded0", "place of worship"],
        ["\ud83d\uded1", "octagonal sign"],
        ["\ud83d\uded2", "shopping trolley"],
        ["\ud83d\uded3", "stupa"],
        ["\ud83d\uded4", "pagoda"],
        ["\ud83d\uded5", "hindu temple"],
        ["\ud83d\uded6", "hut"],
        ["\ud83d\uded7", "elevator"],
        ["\ud83d\udedc", "wireless"],
        ["\ud83d\udedd", "playground slide"],
        ["\ud83d\udede", "wheel"],
        ["\ud83d\udedf", "ring buoy"],
        ["\ud83d\udee0", "hammer and wrench"],
        ["\ud83d\udee1", "shield"],
        ["\ud83d\udee2", "oil drum"],
        ["\ud83d\udee3", "motorway"],
        ["\ud83d\udee4", "railway track"],
        ["\ud83d\udee5", "motor boat"],
        ["\ud83d\udee6", "up-pointing military airplane"],
        ["\ud83d\udee7", "up-pointing airplane"],
        ["\ud83d\udee8", "up-pointing small airplane"],
        ["\ud83d\udee9", "small airplane"],
        ["\ud83d\udeea", "northeast-pointing airplane"],
        ["\ud83d\udeeb", "airplane departure"],
        ["\ud83d\udeec", "airplane arriving"],
        ["\ud83d\udef0", "satellite"],
        ["\ud83d\udef1", "oncoming fire engine"],
        ["\ud83d\udef2", "diesel locomotive"],
        ["\ud83d\udef3", "passenger ship"],
        ["\ud83d\udef4", "scooter"],
        ["\ud83d\udef5", "motor scooter"],
        ["\ud83d\udef6", "canoe"],
        ["\ud83d\udef7", "sled"],
        ["\ud83d\udef8", "flying saucer"],
        ["\ud83d\udef9", "skateboard"],
        ["\ud83d\udefa", "auto rickshaw"],
        ["\ud83d\udefb", "pickup truck"],
        ["\ud83d\udefc", "roller skate"],
        ["\ud83e\udd00", "circled cross formee with four dots"],
        ["\ud83e\udd01", "circled cross formee with two dots"],
        ["\ud83e\udd02", "circled cross formee"],
        ["\ud83e\udd03", "left half circle with four dots"],
        ["\ud83e\udd04", "left half circle with three dots"],
        ["\ud83e\udd05", "left half circle with two dots"],
        ["\ud83e\udd06", "left half circle with dot"],
        ["\ud83e\udd07", "left half circle"],
        ["\ud83e\udd08", "downward facing hook"],
        ["\ud83e\udd09", "downward facing notched hook"],
        ["\ud83e\udd0a", "downward facing hook with dot"],
        ["\ud83e\udd0b", "downward facing notched hook with dot"],
        ["\ud83e\udd0c", "pinched fingers"],
        ["\ud83e\udd0d", "white heart"],
        ["\ud83e\udd0e", "brown heart"],
        ["\ud83e\udd0f", "pinching hand"],
        ["\ud83e\udd10", "zipper-mouth face"],
        ["\ud83e\udd11", "money-mouth face"],
        ["\ud83e\udd12", "face with thermometer"],
        ["\ud83e\udd13", "nerd face"],
        ["\ud83e\udd14", "thinking face"],
        ["\ud83e\udd15", "face with head-bandage"],
        ["\ud83e\udd16", "robot face"],
        ["\ud83e\udd17", "hugging face"],
        ["\ud83e\udd18", "sign of the horns"],
        ["\ud83e\udd19", "call me hand"],
        ["\ud83e\udd1a", "raised back of hand"],
        ["\ud83e\udd1b", "left-facing fist"],
        ["\ud83e\udd1c", "right-facing fist"],
        ["\ud83e\udd1d", "handshake"],
        ["\ud83e\udd1e", "hand with index and middle fingers crossed"],
        ["\ud83e\udd1f", "i love you hand sign"],
        ["\ud83e\udd20", "face with cowboy hat"],
        ["\ud83e\udd21", "clown face"],
        ["\ud83e\udd22", "nauseated face"],
        ["\ud83e\udd23", "rolling on the floor laughing"],
        ["\ud83e\udd24", "drooling face"],
        ["\ud83e\udd25", "lying face"],
        ["\ud83e\udd26", "face palm"],
        ["\ud83e\udd27", "sneezing face"],
        ["\ud83e\udd28", "face with one eyebrow raised"],
        ["\ud83e\udd29", "grinning face with star eyes"],
        ["\ud83e\udd2a", "grinning face with one large and one small eye"],
        ["\ud83e\udd2b", "face with finger covering closed lips"],
        ["\ud83e\udd2c", "serious face with symbols covering mouth"],
        ["\ud83e\udd2d", "smiling face with smiling eyes and hand covering mouth"],
        ["\ud83e\udd2e", "face with open mouth vomiting"],
        ["\ud83e\udd2f", "shocked face with exploding head"],
        ["\ud83e\udd30", "pregnant woman"],
        ["\ud83e\udd31", "breast-feeding"],
        ["\ud83e\udd32", "palms up together"],
        ["\ud83e\udd33", "selfie"],
        ["\ud83e\udd34", "prince"],
        ["\ud83e\udd35", "man in tuxedo"],
        ["\ud83e\udd36", "mother christmas"],
        ["\ud83e\udd37", "shrug"],
        ["\ud83e\udd38", "person doing cartwheel"],
        ["\ud83e\udd39", "juggling"],
        ["\ud83e\udd3a", "fencer"],
        ["\ud83e\udd3b", "modern pentathlon"],
        ["\ud83e\udd3c", "wrestlers"],
        ["\ud83e\udd3d", "water polo"],
        ["\ud83e\udd3e", "handball"],
        ["\ud83e\udd3f", "diving mask"],
        ["\ud83e\udd40", "wilted flower"],
        ["\ud83e\udd41", "drum with drumsticks"],
        ["\ud83e\udd42", "clinking glasses"],
        ["\ud83e\udd43", "tumbler glass"],
        ["\ud83e\udd44", "spoon"],
        ["\ud83e\udd45", "goal net"],
        ["\ud83e\udd46", "rifle"],
        ["\ud83e\udd47", "first place medal"],
        ["\ud83e\udd48", "second place medal"],
        ["\ud83e\udd49", "third place medal"],
        ["\ud83e\udd4a", "boxing glove"],
        ["\ud83e\udd4b", "martial arts uniform"],
        ["\ud83e\udd4c", "curling stone"],
        ["\ud83e\udd4d", "lacrosse stick and ball"],
        ["\ud83e\udd4e", "softball"],
        ["\ud83e\udd4f", "flying disc"],
        ["\ud83e\udd50", "croissant"],
        ["\ud83e\udd51", "avocado"],
        ["\ud83e\udd52", "cucumber"],
        ["\ud83e\udd53", "bacon"],
        ["\ud83e\udd54", "potato"],
        ["\ud83e\udd55", "carrot"],
        ["\ud83e\udd56", "baguette bread"],
        ["\ud83e\udd57", "green salad"],
        ["\ud83e\udd58", "shallow pan of food"],
        ["\ud83e\udd59", "stuffed flatbread"],
        ["\ud83e\udd5a", "egg"],
        ["\ud83e\udd5b", "glass of milk"],
        ["\ud83e\udd5c", "peanuts"],
        ["\ud83e\udd5d", "kiwifruit"],
        ["\ud83e\udd5e", "pancakes"],
        ["\ud83e\udd5f", "dumpling"],
        ["\ud83e\udd60", "fortune cookie"],
        ["\ud83e\udd61", "takeout box"],
        ["\ud83e\udd62", "chopsticks"],
        ["\ud83e\udd63", "bowl with spoon"],
        ["\ud83e\udd64", "cup with straw"],
        ["\ud83e\udd65", "coconut"],
        ["\ud83e\udd66", "broccoli"],
        ["\ud83e\udd67", "pie"],
        ["\ud83e\udd68", "pretzel"],
        ["\ud83e\udd69", "cut of meat"],
        ["\ud83e\udd6a", "sandwich"],
        ["\ud83e\udd6b", "canned food"],
        ["\ud83e\udd6c", "leafy green"],
        ["\ud83e\udd6d", "mango"],
        ["\ud83e\udd6e", "moon cake"],
        ["\ud83e\udd6f", "bagel"],
        ["\ud83e\udd70", "smiling face with smiling eyes and three hearts"],
        ["\ud83e\udd71", "yawning face"],
        ["\ud83e\udd72", "smiling face with tear"],
        ["\ud83e\udd73", "face with party horn and party hat"],
        ["\ud83e\udd74", "face with uneven eyes and wavy mouth"],
        ["\ud83e\udd75", "overheated face"],
        ["\ud83e\udd76", "freezing face"],
        ["\ud83e\udd77", "ninja"],
        ["\ud83e\udd78", "disguised face"],
        ["\ud83e\udd79", "face holding back tears"],
        ["\ud83e\udd7a", "face with pleading eyes"],
        ["\ud83e\udd7b", "sari"],
        ["\ud83e\udd7c", "lab coat"],
        ["\ud83e\udd7d", "goggles"],
        ["\ud83e\udd7e", "hiking boot"],
        ["\ud83e\udd7f", "flat shoe"],
        ["\ud83e\udd80", "crab"],
        ["\ud83e\udd81", "lion face"],
        ["\ud83e\udd82", "scorpion"],
        ["\ud83e\udd83", "turkey"],
        ["\ud83e\udd84", "unicorn face"],
        ["\ud83e\udd85", "eagle"],
        ["\ud83e\udd86", "duck"],
        ["\ud83e\udd87", "bat"],
        ["\ud83e\udd88", "shark"],
        ["\ud83e\udd89", "owl"],
        ["\ud83e\udd8a", "fox face"],
        ["\ud83e\udd8b", "butterfly"],
        ["\ud83e\udd8c", "deer"],
        ["\ud83e\udd8d", "gorilla"],
        ["\ud83e\udd8e", "lizard"],
        ["\ud83e\udd8f", "rhinoceros"],
        ["\ud83e\udd90", "shrimp"],
        ["\ud83e\udd91", "squid"],
        ["\ud83e\udd92", "giraffe face"],
        ["\ud83e\udd93", "zebra face"],
        ["\ud83e\udd94", "hedgehog"],
        ["\ud83e\udd95", "sauropod"],
        ["\ud83e\udd96", "t-rex"],
        ["\ud83e\udd97", "cricket"],
        ["\ud83e\udd98", "kangaroo"],
        ["\ud83e\udd99", "llama"],
        ["\ud83e\udd9a", "peacock"],
        ["\ud83e\udd9b", "hippopotamus"],
        ["\ud83e\udd9c", "parrot"],
        ["\ud83e\udd9d", "raccoon"],
        ["\ud83e\udd9e", "lobster"],
        ["\ud83e\udd9f", "mosquito"],
        ["\ud83e\udda0", "microbe"],
        ["\ud83e\udda1", "badger"],
        ["\ud83e\udda2", "swan"],
        ["\ud83e\udda3", "mammoth"],
        ["\ud83e\udda4", "dodo"],
        ["\ud83e\udda5", "sloth"],
        ["\ud83e\udda6", "otter"],
        ["\ud83e\udda7", "orangutan"],
        ["\ud83e\udda8", "skunk"],
        ["\ud83e\udda9", "flamingo"],
        ["\ud83e\uddaa", "oyster"],
        ["\ud83e\uddab", "beaver"],
        ["\ud83e\uddac", "bison"],
        ["\ud83e\uddad", "seal"],
        ["\ud83e\uddae", "guide dog"],
        ["\ud83e\uddaf", "probing cane"],
        ["\ud83e\uddb0", "emoji component red hair"],
        ["\ud83e\uddb1", "emoji component curly hair"],
        ["\ud83e\uddb2", "emoji component bald"],
        ["\ud83e\uddb3", "emoji component white hair"],
        ["\ud83e\uddb4", "bone"],
        ["\ud83e\uddb5", "leg"],
        ["\ud83e\uddb6", "foot"],
        ["\ud83e\uddb7", "tooth"],
        ["\ud83e\uddb8", "superhero"],
        ["\ud83e\uddb9", "supervillain"],
        ["\ud83e\uddba", "safety vest"],
        ["\ud83e\uddbb", "ear with hearing aid"],
        ["\ud83e\uddbc", "motorized wheelchair"],
        ["\ud83e\uddbd", "manual wheelchair"],
        ["\ud83e\uddbe", "mechanical arm"],
        ["\ud83e\uddbf", "mechanical leg"],
        ["\ud83e\uddc0", "cheese wedge"],
        ["\ud83e\uddc1", "cupcake"],
        ["\ud83e\uddc2", "salt shaker"],
        ["\ud83e\uddc3", "beverage box"],
        ["\ud83e\uddc4", "garlic"],
        ["\ud83e\uddc5", "onion"],
        ["\ud83e\uddc6", "falafel"],
        ["\ud83e\uddc7", "waffle"],
        ["\ud83e\uddc8", "butter"],
        ["\ud83e\uddc9", "mate drink"],
        ["\ud83e\uddca", "ice cube"],
        ["\ud83e\uddcb", "bubble tea"],
        ["\ud83e\uddcc", "troll"],
        ["\ud83e\uddcd", "standing person"],
        ["\ud83e\uddce", "kneeling person"],
        ["\ud83e\uddcf", "deaf person"],
        ["\ud83e\uddd0", "face with monocle"],
        ["\ud83e\uddd1", "adult"],
        ["\ud83e\uddd2", "child"],
        ["\ud83e\uddd3", "older adult"],
        ["\ud83e\uddd4", "bearded person"],
        ["\ud83e\uddd5", "person with headscarf"],
        ["\ud83e\uddd6", "person in steamy room"],
        ["\ud83e\uddd7", "person climbing"],
        ["\ud83e\uddd8", "person in lotus position"],
        ["\ud83e\uddd9", "mage"],
        ["\ud83e\uddda", "fairy"],
        ["\ud83e\udddb", "vampire"],
        ["\ud83e\udddc", "merperson"],
        ["\ud83e\udddd", "elf"],
        ["\ud83e\uddde", "genie"],
        ["\ud83e\udddf", "zombie"],
        ["\ud83e\udde0", "brain"],
        ["\ud83e\udde1", "orange heart"],
        ["\ud83e\udde2", "billed cap"],
        ["\ud83e\udde3", "scarf"],
        ["\ud83e\udde4", "gloves"],
        ["\ud83e\udde5", "coat"],
        ["\ud83e\udde6", "socks"],
        ["\ud83e\udde7", "red gift envelope"],
        ["\ud83e\udde8", "firecracker"],
        ["\ud83e\udde9", "jigsaw puzzle piece"],
        ["\ud83e\uddea", "test tube"],
        ["\ud83e\uddeb", "petri dish"],
        ["\ud83e\uddec", "dna double helix"],
        ["\ud83e\udded", "compass"],
        ["\ud83e\uddee", "abacus"],
        ["\ud83e\uddef", "fire extinguisher"],
        ["\ud83e\uddf0", "toolbox"],
        ["\ud83e\uddf1", "brick"],
        ["\ud83e\uddf2", "magnet"],
        ["\ud83e\uddf3", "luggage"],
        ["\ud83e\uddf4", "lotion bottle"],
        ["\ud83e\uddf5", "spool of thread"],
        ["\ud83e\uddf6", "ball of yarn"],
        ["\ud83e\uddf7", "safety pin"],
        ["\ud83e\uddf8", "teddy bear"],
        ["\ud83e\uddf9", "broom"],
        ["\ud83e\uddfa", "basket"],
        ["\ud83e\uddfb", "roll of paper"],
        ["\ud83e\uddfc", "bar of soap"],
        ["\ud83e\uddfd", "sponge"],
        ["\ud83e\uddfe", "receipt"],
        ["\ud83e\uddff", "nazar amulet"],
        ["\ud83e\ude70", "ballet shoes"],
        ["\ud83e\ude71", "one-piece swimsuit"],
        ["\ud83e\ude72", "briefs"],
        ["\ud83e\ude73", "shorts"],
        ["\ud83e\ude74", "thong sandal"],
        ["\ud83e\ude75", "light blue heart"],
        ["\ud83e\ude76", "grey heart"],
        ["\ud83e\ude77", "pink heart"],
        ["\ud83e\ude78", "drop of blood"],
        ["\ud83e\ude79", "adhesive bandage"],
        ["\ud83e\ude7a", "stethoscope"],
        ["\ud83e\ude7b", "x-ray"],
        ["\ud83e\ude7c", "crutch"],
        ["\ud83e\ude80", "yo-yo"],
        ["\ud83e\ude81", "kite"],
        ["\ud83e\ude82", "parachute"],
        ["\ud83e\ude83", "boomerang"],
        ["\ud83e\ude84", "magic wand"],
        ["\ud83e\ude85", "pinata"],
        ["\ud83e\ude86", "nesting dolls"],
        ["\ud83e\ude87", "maracas"],
        ["\ud83e\ude88", "flute"],
        ["\ud83e\ude89", "harp"],
        ["\ud83e\ude8f", "shovel"],
        ["\ud83e\ude90", "ringed planet"],
        ["\ud83e\ude91", "chair"],
        ["\ud83e\ude92", "razor"],
        ["\ud83e\ude93", "axe"],
        ["\ud83e\ude94", "diya lamp"],
        ["\ud83e\ude95", "banjo"],
        ["\ud83e\ude96", "military helmet"],
        ["\ud83e\ude97", "accordion"],
        ["\ud83e\ude98", "long drum"],
        ["\ud83e\ude99", "coin"],
        ["\ud83e\ude9a", "carpentry saw"],
        ["\ud83e\ude9b", "screwdriver"],
        ["\ud83e\ude9c", "ladder"],
        ["\ud83e\ude9d", "hook"],
        ["\ud83e\ude9e", "mirror"],
        ["\ud83e\ude9f", "window"],
        ["\ud83e\udea0", "plunger"],
        ["\ud83e\udea1", "sewing needle"],
        ["\ud83e\udea2", "knot"],
        ["\ud83e\udea3", "bucket"],
        ["\ud83e\udea4", "mouse trap"],
        ["\ud83e\udea5", "toothbrush"],
        ["\ud83e\udea6", "headstone"],
        ["\ud83e\udea7", "placard"],
        ["\ud83e\udea8", "rock"],
        ["\ud83e\udea9", "mirror ball"],
        ["\ud83e\udeaa", "identification card"],
        ["\ud83e\udeab", "low battery"],
        ["\ud83e\udeac", "hamsa"],
        ["\ud83e\udead", "folding hand fan"],
        ["\ud83e\udeae", "hair pick"],
        ["\ud83e\udeaf", "khanda"],
        ["\ud83e\udeb0", "fly"],
        ["\ud83e\udeb1", "worm"],
        ["\ud83e\udeb2", "beetle"],
        ["\ud83e\udeb3", "cockroach"],
        ["\ud83e\udeb4", "potted plant"],
        ["\ud83e\udeb5", "wood"],
        ["\ud83e\udeb6", "feather"],
        ["\ud83e\udeb7", "lotus"],
        ["\ud83e\udeb8", "coral"],
        ["\ud83e\udeb9", "empty nest"],
        ["\ud83e\udeba", "nest with eggs"],
        ["\ud83e\udebb", "hyacinth"],
        ["\ud83e\udebc", "jellyfish"],
        ["\ud83e\udebd", "wing"],
        ["\ud83e\udebe", "leafless tree"],
        ["\ud83e\udebf", "goose"],
        ["\ud83e\udec0", "anatomical heart"],
        ["\ud83e\udec1", "lungs"],
        ["\ud83e\udec2", "people hugging"],
        ["\ud83e\udec3", "pregnant man"],
        ["\ud83e\udec4", "pregnant person"],
        ["\ud83e\udec5", "person with crown"],
        ["\ud83e\udec6", "fingerprint"],
        ["\ud83e\udece", "moose"],
        ["\ud83e\udecf", "donkey"],
        ["\ud83e\uded0", "blueberries"],
        ["\ud83e\uded1", "bell pepper"],
        ["\ud83e\uded2", "olive"],
        ["\ud83e\uded3", "flatbread"],
        ["\ud83e\uded4", "tamale"],
        ["\ud83e\uded5", "fondue"],
        ["\ud83e\uded6", "teapot"],
        ["\ud83e\uded7", "pouring liquid"],
        ["\ud83e\uded8", "beans"],
        ["\ud83e\uded9", "jar"],
        ["\ud83e\udeda", "ginger root"],
        ["\ud83e\udedb", "pea pod"],
        ["\ud83e\udedc", "root vegetable"],
        ["\ud83e\udedf", "splatter"],
        ["\ud83e\udee0", "melting face"],
        ["\ud83e\udee1", "saluting face"],
        ["\ud83e\udee2", "face with open eyes and hand over mouth"],
        ["\ud83e\udee3", "face with peeking eye"],
        ["\ud83e\udee4", "face with diagonal mouth"],
        ["\ud83e\udee5", "dotted line face"],
        ["\ud83e\udee6", "biting lip"],
        ["\ud83e\udee7", "bubbles"],
        ["\ud83e\udee8", "shaking face"],
        ["\ud83e\udee9", "face with bags under eyes"],
        ["\ud83e\udef0", "hand with index finger and thumb crossed"],
        ["\ud83e\udef1", "rightwards hand"],
        ["\ud83e\udef2", "leftwards hand"],
        ["\ud83e\udef3", "palm down hand"],
        ["\ud83e\udef4", "palm up hand"],
        ["\ud83e\udef5", "index pointing at the viewer"],
        ["\ud83e\udef6", "heart hands"],
        ["\ud83e\udef7", "leftwards pushing hand"],
        ["\ud83e\udef8", "rightwards pushing hand"],
        ["\u2600", "black sun with rays"],
        ["\u2601", "cloud"],
        ["\u2602", "umbrella"],
        ["\u2603", "snowman"],
        ["\u2604", "comet"],
        ["\u2605", "black star"],
        ["\u2606", "white star"],
        ["\u2607", "lightning"],
        ["\u2608", "thunderstorm"],
        ["\u2609", "sun"],
        ["\u260a", "ascending node"],
        ["\u260b", "descending node"],
        ["\u260c", "conjunction"],
        ["\u260d", "opposition"],
        ["\u260e", "black telephone"],
        ["\u260f", "white telephone"],
        ["\u2610", "ballot box"],
        ["\u2611", "ballot box with check"],
        ["\u2612", "ballot box with x"],
        ["\u2613", "saltire"],
        ["\u2614", "umbrella with rain drops"],
        ["\u2615", "hot beverage"],
        ["\u2616", "white shogi piece"],
        ["\u2617", "black shogi piece"],
        ["\u2618", "shamrock"],
        ["\u2619", "reversed rotated floral heart bullet"],
        ["\u261a", "black left pointing index"],
        ["\u261b", "black right pointing index"],
        ["\u261c", "white left pointing index"],
        ["\u261d", "white up pointing index"],
        ["\u261e", "white right pointing index"],
        ["\u261f", "white down pointing index"],
        ["\u2620", "skull and crossbones"],
        ["\u2621", "caution sign"],
        ["\u2622", "radioactive sign"],
        ["\u2623", "biohazard sign"],
        ["\u2624", "caduceus"],
        ["\u2625", "ankh"],
        ["\u2626", "orthodox cross"],
        ["\u2627", "chi rho"],
        ["\u2628", "cross of lorraine"],
        ["\u2629", "cross of jerusalem"],
        ["\u262a", "star and crescent"],
        ["\u262b", "farsi symbol"],
        ["\u262c", "adi shakti"],
        ["\u262d", "hammer and sickle"],
        ["\u262e", "peace symbol"],
        ["\u262f", "yin yang"],
        ["\u2630", "trigram for heaven"],
        ["\u2631", "trigram for lake"],
        ["\u2632", "trigram for fire"],
        ["\u2633", "trigram for thunder"],
        ["\u2634", "trigram for wind"],
        ["\u2635", "trigram for water"],
        ["\u2636", "trigram for mountain"],
        ["\u2637", "trigram for earth"],
        ["\u2638", "wheel of dharma"],
        ["\u2639", "white frowning face"],
        ["\u263a", "white smiling face"],
        ["\u263b", "black smiling face"],
        ["\u263c", "white sun with rays"],
        ["\u263d", "first quarter moon"],
        ["\u263e", "last quarter moon"],
        ["\u263f", "mercury"],
        ["\u2640", "female sign"],
        ["\u2641", "earth"],
        ["\u2642", "male sign"],
        ["\u2643", "jupiter"],
        ["\u2644", "saturn"],
        ["\u2645", "uranus"],
        ["\u2646", "neptune"],
        ["\u2647", "pluto"],
        ["\u2648", "aries"],
        ["\u2649", "taurus"],
        ["\u264a", "gemini"],
        ["\u264b", "cancer"],
        ["\u264c", "leo"],
        ["\u264d", "virgo"],
        ["\u264e", "libra"],
        ["\u264f", "scorpius"],
        ["\u2650", "sagittarius"],
        ["\u2651", "capricorn"],
        ["\u2652", "aquarius"],
        ["\u2653", "pisces"],
        ["\u2654", "white chess king"],
        ["\u2655", "white chess queen"],
        ["\u2656", "white chess rook"],
        ["\u2657", "white chess bishop"],
        ["\u2658", "white chess knight"],
        ["\u2659", "white chess pawn"],
        ["\u265a", "black chess king"],
        ["\u265b", "black chess queen"],
        ["\u265c", "black chess rook"],
        ["\u265d", "black chess bishop"],
        ["\u265e", "black chess knight"],
        ["\u265f", "black chess pawn"],
        ["\u2660", "black spade suit"],
        ["\u2661", "white heart suit"],
        ["\u2662", "white diamond suit"],
        ["\u2663", "black club suit"],
        ["\u2664", "white spade suit"],
        ["\u2665", "black heart suit"],
        ["\u2666", "black diamond suit"],
        ["\u2667", "white club suit"],
        ["\u2668", "hot springs"],
        ["\u2669", "quarter note"],
        ["\u266a", "eighth note"],
        ["\u266b", "beamed eighth notes"],
        ["\u266c", "beamed sixteenth notes"],
        ["\u266d", "music flat sign"],
        ["\u266e", "music natural sign"],
        ["\u2670", "west syriac cross"],
        ["\u2671", "east syriac cross"],
        ["\u2672", "universal recycling symbol"],
        ["\u2673", "recycling symbol for type-1 plastics"],
        ["\u2674", "recycling symbol for type-2 plastics"],
        ["\u2675", "recycling symbol for type-3 plastics"],
        ["\u2676", "recycling symbol for type-4 plastics"],
        ["\u2677", "recycling symbol for type-5 plastics"],
        ["\u2678", "recycling symbol for type-6 plastics"],
        ["\u2679", "recycling symbol for type-7 plastics"],
        ["\u267a", "recycling symbol for generic materials"],
        ["\u267b", "black universal recycling symbol"],
        ["\u267c", "recycled paper symbol"],
        ["\u267d", "partially-recycled paper symbol"],
        ["\u267e", "permanent paper sign"],
        ["\u267f", "wheelchair symbol"],
        ["\u2680", "die face-1"],
        ["\u2681", "die face-2"],
        ["\u2682", "die face-3"],
        ["\u2683", "die face-4"],
        ["\u2684", "die face-5"],
        ["\u2685", "die face-6"],
        ["\u2686", "white circle with dot right"],
        ["\u2687", "white circle with two dots"],
        ["\u2688", "black circle with white dot right"],
        ["\u2689", "black circle with two white dots"],
        ["\u268a", "monogram for yang"],
        ["\u268b", "monogram for yin"],
        ["\u268c", "digram for greater yang"],
        ["\u268d", "digram for lesser yin"],
        ["\u268e", "digram for lesser yang"],
        ["\u268f", "digram for greater yin"],
        ["\u2690", "white flag"],
        ["\u2691", "black flag"],
        ["\u2692", "hammer and pick"],
        ["\u2693", "anchor"],
        ["\u2694", "crossed swords"],
        ["\u2695", "staff of aesculapius"],
        ["\u2696", "scales"],
        ["\u2697", "alembic"],
        ["\u2698", "flower"],
        ["\u2699", "gear"],
        ["\u269a", "staff of hermes"],
        ["\u269b", "atom symbol"],
        ["\u269c", "fleur-de-lis"],
        ["\u269d", "outlined white star"],
        ["\u269e", "three lines converging right"],
        ["\u269f", "three lines converging left"],
        ["\u26a0", "warning sign"],
        ["\u26a1", "high voltage sign"],
        ["\u26a2", "doubled female sign"],
        ["\u26a3", "doubled male sign"],
        ["\u26a4", "interlocked female and male sign"],
        ["\u26a5", "male and female sign"],
        ["\u26a6", "male with stroke sign"],
        ["\u26a7", "male with stroke and male and female sign"],
        ["\u26a8", "vertical male with stroke sign"],
        ["\u26a9", "horizontal male with stroke sign"],
        ["\u26aa", "medium white circle"],
        ["\u26ab", "medium black circle"],
        ["\u26ac", "medium small white circle"],
        ["\u26ad", "marriage symbol"],
        ["\u26ae", "divorce symbol"],
        ["\u26af", "unmarried partnership symbol"],
        ["\u26b0", "coffin"],
        ["\u26b1", "funeral urn"],
        ["\u26b2", "neuter"],
        ["\u26b3", "ceres"],
        ["\u26b4", "pallas"],
        ["\u26b5", "juno"],
        ["\u26b6", "vesta"],
        ["\u26b7", "chiron"],
        ["\u26b8", "black moon lilith"],
        ["\u26b9", "sextile"],
        ["\u26ba", "semisextile"],
        ["\u26bb", "quincunx"],
        ["\u26bc", "sesquiquadrate"],
        ["\u26bd", "soccer ball"],
        ["\u26be", "baseball"],
        ["\u26bf", "squared key"],
        ["\u26c0", "white draughts man"],
        ["\u26c1", "white draughts king"],
        ["\u26c2", "black draughts man"],
        ["\u26c3", "black draughts king"],
        ["\u26c4", "snowman without snow"],
        ["\u26c5", "sun behind cloud"],
        ["\u26c6", "rain"],
        ["\u26c7", "black snowman"],
        ["\u26c8", "thunder cloud and rain"],
        ["\u26c9", "turned white shogi piece"],
        ["\u26ca", "turned black shogi piece"],
        ["\u26cb", "white diamond in square"],
        ["\u26cc", "crossing lanes"],
        ["\u26cd", "disabled car"],
        ["\u26ce", "ophiuchus"],
        ["\u26cf", "pick"],
        ["\u26d0", "car sliding"],
        ["\u26d1", "helmet with white cross"],
        ["\u26d2", "circled crossing lanes"],
        ["\u26d3", "chains"],
        ["\u26d4", "no entry"],
        ["\u26d5", "alternate one-way left way traffic"],
        ["\u26d6", "black two-way left way traffic"],
        ["\u26d7", "white two-way left way traffic"],
        ["\u26d8", "black left lane merge"],
        ["\u26d9", "white left lane merge"],
        ["\u26da", "drive slow sign"],
        ["\u26db", "heavy white down-pointing triangle"],
        ["\u26dc", "left closed entry"],
        ["\u26dd", "squared saltire"],
        ["\u26de", "falling diagonal in white circle in black square"],
        ["\u26df", "black truck"],
        ["\u26e0", "restricted left entry-1"],
        ["\u26e1", "restricted left entry-2"],
        ["\u26e2", "astronomical symbol for uranus"],
        ["\u26e3", "heavy circle with stroke and two dots above"],
        ["\u26e4", "pentagram"],
        ["\u26e5", "right-handed interlaced pentagram"],
        ["\u26e6", "left-handed interlaced pentagram"],
        ["\u26e7", "inverted pentagram"],
        ["\u26e8", "black cross on shield"],
        ["\u26e9", "shinto shrine"],
        ["\u26ea", "church"],
        ["\u26eb", "castle"],
        ["\u26ec", "historic site"],
        ["\u26ed", "gear without hub"],
        ["\u26ee", "gear with handles"],
        ["\u26ef", "map symbol for lighthouse"],
        ["\u26f0", "mountain"],
        ["\u26f1", "umbrella on ground"],
        ["\u26f2", "fountain"],
        ["\u26f3", "flag in hole"],
        ["\u26f4", "ferry"],
        ["\u26f5", "sailboat"],
        ["\u26f6", "square four corners"],
        ["\u26f7", "skier"],
        ["\u26f8", "ice skate"],
        ["\u26f9", "person with ball"],
        ["\u26fa", "tent"],
        ["\u26fb", "japanese bank symbol"],
        ["\u26fc", "headstone graveyard symbol"],
        ["\u26fd", "fuel pump"],
        ["\u26fe", "cup on black square"],
        ["\u26ff", "white flag with horizontal middle black stripe"],
        ["\u2700", "black safety scissors"],
        ["\u2701", "upper blade scissors"],
        ["\u2702", "black scissors"],
        ["\u2703", "lower blade scissors"],
        ["\u2704", "white scissors"],
        ["\u2705", "white heavy check mark"],
        ["\u2706", "telephone location sign"],
        ["\u2707", "tape drive"],
        ["\u2708", "airplane"],
        ["\u2709", "envelope"],
        ["\u270a", "raised fist"],
        ["\u270b", "raised hand"],
        ["\u270c", "victory hand"],
        ["\u270d", "writing hand"],
        ["\u270e", "lower right pencil"],
        ["\u270f", "pencil"],
        ["\u2710", "upper right pencil"],
        ["\u2711", "white nib"],
        ["\u2712", "black nib"],
        ["\u2713", "check mark"],
        ["\u2714", "heavy check mark"],
        ["\u2715", "multiplication x"],
        ["\u2716", "heavy multiplication x"],
        ["\u2717", "ballot x"],
        ["\u2718", "heavy ballot x"],
        ["\u2719", "outlined greek cross"],
        ["\u271a", "heavy greek cross"],
        ["\u271b", "open centre cross"],
        ["\u271c", "heavy open centre cross"],
        ["\u271d", "latin cross"],
        ["\u271e", "shadowed white latin cross"],
        ["\u271f", "outlined latin cross"],
        ["\u2720", "maltese cross"],
        ["\u2721", "star of david"],
        ["\u2722", "four teardrop-spoked asterisk"],
        ["\u2723", "four balloon-spoked asterisk"],
        ["\u2724", "heavy four balloon-spoked asterisk"],
        ["\u2725", "four club-spoked asterisk"],
        ["\u2726", "black four pointed star"],
        ["\u2727", "white four pointed star"],
        ["\u2728", "sparkles"],
        ["\u2729", "stress outlined white star"],
        ["\u272a", "circled white star"],
        ["\u272b", "open centre black star"],
        ["\u272c", "black centre white star"],
        ["\u272d", "outlined black star"],
        ["\u272e", "heavy outlined black star"],
        ["\u272f", "pinwheel star"],
        ["\u2730", "shadowed white star"],
        ["\u2731", "heavy asterisk"],
        ["\u2732", "open centre asterisk"],
        ["\u2733", "eight spoked asterisk"],
        ["\u2734", "eight pointed black star"],
        ["\u2735", "eight pointed pinwheel star"],
        ["\u2736", "six pointed black star"],
        ["\u2737", "eight pointed rectilinear black star"],
        ["\u2738", "heavy eight pointed rectilinear black star"],
        ["\u2739", "twelve pointed black star"],
        ["\u273a", "sixteen pointed asterisk"],
        ["\u273b", "teardrop-spoked asterisk"],
        ["\u273c", "open centre teardrop-spoked asterisk"],
        ["\u273d", "heavy teardrop-spoked asterisk"],
        ["\u273e", "six petalled black and white florette"],
        ["\u273f", "black florette"],
        ["\u2740", "white florette"],
        ["\u2741", "eight petalled outlined black florette"],
        ["\u2742", "circled open centre eight pointed star"],
        ["\u2743", "heavy teardrop-spoked pinwheel asterisk"],
        ["\u2744", "snowflake"],
        ["\u2745", "tight trifoliate snowflake"],
        ["\u2746", "heavy chevron snowflake"],
        ["\u2747", "sparkle"],
        ["\u2748", "heavy sparkle"],
        ["\u2749", "balloon-spoked asterisk"],
        ["\u274a", "eight teardrop-spoked propeller asterisk"],
        ["\u274b", "heavy eight teardrop-spoked propeller asterisk"],
        ["\u274c", "cross mark"],
        ["\u274d", "shadowed white circle"],
        ["\u274e", "negative squared cross mark"],
        ["\u274f", "lower right drop-shadowed white square"],
        ["\u2750", "upper right drop-shadowed white square"],
        ["\u2751", "lower right shadowed white square"],
        ["\u2752", "upper right shadowed white square"],
        ["\u2753", "black question mark ornament"],
        ["\u2754", "white question mark ornament"],
        ["\u2755", "white exclamation mark ornament"],
        ["\u2756", "black diamond minus white x"],
        ["\u2757", "heavy exclamation mark symbol"],
        ["\u2758", "light vertical bar"],
        ["\u2759", "medium vertical bar"],
        ["\u275a", "heavy vertical bar"],
        ["\u275b", "heavy single turned comma quotation mark ornament"],
        ["\u275c", "heavy single comma quotation mark ornament"],
        ["\u275d", "heavy double turned comma quotation mark ornament"],
        ["\u275e", "heavy double comma quotation mark ornament"],
        ["\u275f", "heavy low single comma quotation mark ornament"],
        ["\u2760", "heavy low double comma quotation mark ornament"],
        ["\u2761", "curved stem paragraph sign ornament"],
        ["\u2762", "heavy exclamation mark ornament"],
        ["\u2763", "heavy heart exclamation mark ornament"],
        ["\u2764", "heavy black heart"],
        ["\u2765", "rotated heavy black heart bullet"],
        ["\u2766", "floral heart"],
        ["\u2767", "rotated floral heart bullet"],
        ["\u2794", "heavy wide-headed rightwards arrow"],
        ["\u2795", "heavy plus sign"],
        ["\u2796", "heavy minus sign"],
        ["\u2797", "heavy division sign"],
        ["\u2798", "heavy south east arrow"],
        ["\u2799", "heavy rightwards arrow"],
        ["\u279a", "heavy north east arrow"],
        ["\u279b", "drafting point rightwards arrow"],
        ["\u279c", "heavy round-tipped rightwards arrow"],
        ["\u279d", "triangle-headed rightwards arrow"],
        ["\u279e", "heavy triangle-headed rightwards arrow"],
        ["\u279f", "dashed triangle-headed rightwards arrow"],
        ["\u27a0", "heavy dashed triangle-headed rightwards arrow"],
        ["\u27a1", "black rightwards arrow"],
        ["\u27a2", "three-d top-lighted rightwards arrowhead"],
        ["\u27a3", "three-d bottom-lighted rightwards arrowhead"],
        ["\u27a4", "black rightwards arrowhead"],
        ["\u27a5", "heavy black curved downwards and rightwards arrow"],
        ["\u27a6", "heavy black curved upwards and rightwards arrow"],
        ["\u27a7", "squat black rightwards arrow"],
        ["\u27a8", "heavy concave-pointed black rightwards arrow"],
        ["\u27a9", "right-shaded white rightwards arrow"],
        ["\u27aa", "left-shaded white rightwards arrow"],
        ["\u27ab", "back-tilted shadowed white rightwards arrow"],
        ["\u27ac", "front-tilted shadowed white rightwards arrow"],
        ["\u27ad", "heavy lower right-shadowed white rightwards arrow"],
        ["\u27ae", "heavy upper right-shadowed white rightwards arrow"],
        ["\u27af", "notched lower right-shadowed white rightwards arrow"],
        ["\u27b0", "curly loop"],
        ["\u27b1", "notched upper right-shadowed white rightwards arrow"],
        ["\u27b2", "circled heavy white rightwards arrow"],
        ["\u27b3", "white-feathered rightwards arrow"],
        ["\u27b4", "black-feathered south east arrow"],
        ["\u27b5", "black-feathered rightwards arrow"],
        ["\u27b6", "black-feathered north east arrow"],
        ["\u27b7", "heavy black-feathered south east arrow"],
        ["\u27b8", "heavy black-feathered rightwards arrow"],
        ["\u27b9", "heavy black-feathered north east arrow"],
        ["\u27ba", "teardrop-barbed rightwards arrow"],
        ["\u27bb", "heavy teardrop-shanked rightwards arrow"],
        ["\u27bc", "wedge-tailed rightwards arrow"],
        ["\u27bd", "heavy wedge-tailed rightwards arrow"],
        ["\u27be", "open-outlined rightwards arrow"],
        ["\u27bf", "double curly loop"]
    ]
}
